<a href="https://colab.research.google.com/github/fangxiang00/Awesome-Chinese-NLP/blob/master/pytorch1_whatspytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


pytorch是一个基于python的科学计算包，主要针对两类人群：
作为NumPy的替代品，可以利用GPU的性能进行计算
作为一个高灵活性、速度快的深度学习平台


张量
与numpy的区别：可以在GPU上加速计算


In [2]:
x = torch.empty(5,3)
x

tensor([[6.4543e-03, 3.0866e-41, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

In [3]:
"""创建一个随机初始化矩阵"""
x=torch.rand(5,3)
x

tensor([[0.5904, 0.7472, 0.7885],
        [0.2467, 0.0418, 0.6561],
        [0.9885, 0.3263, 0.7670],
        [0.5450, 0.9361, 0.8585],
        [0.5311, 0.8953, 0.8397]])

In [4]:
#创建一个填满0，且数据类型为long的矩阵
x=torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
#直接利用数据构造张量
x=torch.tensor([5.5,3,4,5])
x

tensor([5.5000, 3.0000, 4.0000, 5.0000])

In [6]:
#复制tensor
x=x.new_ones(5,3,dtype=torch.double)
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[-0.5914,  0.0928, -0.8363],
        [-2.1019,  0.8357,  2.1983],
        [ 0.6048, -0.7242,  1.4444],
        [ 0.6958, -0.2723, -0.7216],
        [-0.4729,  0.0562,  0.3149]])

In [7]:
x.size()

torch.Size([5, 3])

In [ ]:
#运算
y=torch.rand(5,3)
torch.add(x+y)
#原地操作，任何一个in-place改变张量的操作后面都固定一个_。例如x.copy_(y)\x.t_()将更改x
y.add_(x)#改变y的值

In [9]:
#索引操作
z=x[:,1]
z
#改变形状：torch.view()
x=torch.randn(4,4)
z=x.view(16)
k=x.view(-1,8)
z,k

(tensor([ 4.1624e-01, -9.6432e-04, -1.3628e+00, -7.9685e-01, -1.7061e+00,
         -6.8051e-01, -6.4959e-01, -4.2707e-01,  2.9561e-01, -1.8531e-01,
          4.3705e-01,  1.1478e+00,  1.2558e+00,  4.3806e-03,  7.3876e-01,
          3.8952e-01]),
 tensor([[ 4.1624e-01, -9.6432e-04, -1.3628e+00, -7.9685e-01, -1.7061e+00,
          -6.8051e-01, -6.4959e-01, -4.2707e-01],
         [ 2.9561e-01, -1.8531e-01,  4.3705e-01,  1.1478e+00,  1.2558e+00,
           4.3806e-03,  7.3876e-01,  3.8952e-01]]))

In [12]:
#如果是只有一个元素的tensor，可以用.item()来得到对应的数值
x=torch.randn(1)
x, x.item()

(tensor([-0.1059]), -0.10591565072536469)

In [13]:
"""tensor与numpy的互相转换"""
#torch转numpy
a=torch.ones(5)
b=a.numpy()
a,b

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [14]:
#torch张量和numpy数组将共享它们的底层内存位置，因此当改变一个时，另一个也会改变
a.add_(1)
a,b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [15]:
#numpy转torch
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
a,b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x=torch.rand(5,device="cpu")
y=torch.ones_like(x,device=device)
#x=x.to(device)
z=x+y
device,x,y,z

(device(type='cpu'),
 tensor([0.1505, 0.7796, 0.6043, 0.8093, 0.2196]),
 tensor([1., 1., 1., 1., 1.]),
 tensor([1.1505, 1.7796, 1.6043, 1.8093, 1.2196]))